-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, sum(O.SALES_AMOUNT*P.PRICE) as sales
FROM OFFLINE_SALE O 
    INNER JOIN PRODUCT P ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
order by sales desc, P.PRODUCT_CODE asc