-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, date_format(DATE_OF_BIRTH, '%Y-%m-%d') as DATE_OF_BIRTH
FROM MEMBER_PROFILE 
WHERE GENDER LIKE 'W' AND
      date_format(DATE_OF_BIRTH, '%m') LIKE '03' AND
      TLNO
ORDER BY MEMBER_ID ASC
      