-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE DATE_FORMAT(START_DATE, '%Y-%m') between '2022-08' and '2022-10' AND
      CAR_ID IN (SELECT CAR_ID
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                WHERE DATE_FORMAT(START_DATE, '%Y-%m') between '2022-08' and '2022-10'
                GROUP BY CAR_ID
                HAVING COUNT(CAR_ID) >= 5)
GROUP BY CAR_ID, MONTH
HAVING RECORDS >= 1
ORDER BY MONTH ASC, CAR_ID DESC